/**
 * The Android output: `values/strings.xml` for the source language and `values-<code>/strings.xml`
 * for the rest, from the same native namespace Swift reads. Nothing consumes it yet — the Android
 * build has no native surfaces — but it is generated and checked from day one, so the first widget
 * written for Android starts with every string already translated.
 *
 * Resource names cannot contain dots: `native.watch.title` becomes `native_watch_title` (the checker
 * refuses two keys that land on one name).
 *
 * A literal `%` is doubled only in a string that takes format arguments: Android runs a resource
 * through `String.format` only when `getString`/`getQuantityString` is given arguments, and without
 * them a `%%` would show as it is.
 *
 * Exact cases (`=0`) are left out: Android's quantities are the language's plural categories, and its
 * `zero` is honoured only by a language that has one, so the number's own form shows there ("0 days"
 * rather than "Nothing"). The checker warns about each one.
 */
import { config, outputsOf } from "../../i18n.config";
import type { Locale } from "../load";
import { argsOf, parse, type Node } from "../parse";

function escape(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/"/g, '\\"').replace(/\n/g, "\\n")
    .replace(/^([@?])/, "\\$1");
}

export function androidName(key: string): string { return key.replace(/\./g, "_"); }

/** Whether anything in the message is a format argument, in any branch. */
function formatted(ast: Node[]): boolean {
  return ast.some((n) => n.t === "arg" || n.t === "pound"
    || (n.t === "tag" && formatted(n.children))
    || ((n.t === "plural" || n.t === "select") && Object.values(n.cases).some(formatted)));
}

function flat(ast: Node[], args: string[], pluralArg: string | null, percent: boolean): string {
  let s = "";
  for (const n of ast) {
    if (n.t === "text") s += percent ? escape(n.v).replace(/%/g, "%%") : escape(n.v);
    else if (n.t === "arg") s += `%${args.indexOf(n.name) + 1}$s`;
    else if (n.t === "pound") s += `%${args.indexOf(pluralArg!) + 1}$d`;
  }
  return s;
}

export function emitAndroid(locales: Map<string, Locale>): Record<string, string> {
  const source = locales.get(config.source)!;
  const keys = [...source.values()].filter((e) => outputsOf(e.namespace).includes("android")).map((e) => e.key).sort();
  const files: Record<string, string> = {};
  for (const { code } of config.languages) {
    const locale = locales.get(code)!;
    const out: string[] = [];
    for (const k of keys) {
      const m = locale.get(k);
      if (!m) continue;
      const name = androidName(k);
      const ast = parse(m.message);
      const percent = formatted(ast);
      const args = [...argsOf(parse(source.get(k)!.message)).keys()];
      const idx = ast.findIndex((n) => n.t === "plural");
      if (idx < 0) { out.push(`  <string name="${name}">${flat(ast, args, null, percent)}</string>`); continue; }
      const p = ast[idx] as Extract<Node, { t: "plural" }>;
      const items = Object.entries(p.cases).filter(([q]) => !q.startsWith("="))
        .map(([q, branch]) => `    <item quantity="${q}">${flat([...ast.slice(0, idx), ...branch, ...ast.slice(idx + 1)], args, p.name, percent)}</item>`);
      out.push(`  <plurals name="${name}">\n${items.join("\n")}\n  </plurals>`);
    }
    const dir = code === config.source ? "values" : `values-${code}`;
    files[`${dir}/strings.xml`] = `<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by \`bun run i18n\` from packages/i18n/locales. Do not edit. -->\n<resources>\n${out.join("\n")}\n</resources>\n`;
  }
  return files;
}
