/**
 * The React Native (and core) output: one catalogue module per language plus `messages.ts`, the type
 * that makes `t("budget.left")` without `{ count }` a compile error.
 */
import { config, outputsOf } from "../../i18n.config";
import { compile } from "../compile";
import type { Locale } from "../load";
import { argsOf, parse } from "../parse";

export function emitTs(locales: Map<string, Locale>): Record<string, string> {
  const files: Record<string, string> = {};
  const header = "// Generated by `bun run i18n` from packages/i18n/locales. Do not edit.\n";
  const source = locales.get(config.source)!;
  const keys = [...source.values()].filter((e) => outputsOf(e.namespace).includes("ts")).map((e) => e.key).sort();

  for (const { code } of config.languages) {
    const locale = locales.get(code)!;
    const body = keys.filter((k) => locale.has(k))
      .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(compile(parse(locale.get(k)!.message)))},`).join("\n");
    files[`${code}.ts`] = `${header}import type { Catalog } from "../runtime";\n\nconst catalog: Catalog = {\n${body}\n};\nexport default catalog;\n`;
  }

  const types = keys.map((k) => {
    const e = source.get(k)!;
    const args = argsOf(parse(e.message));
    const fields = [...args].map(([name, a]) => {
      const type = a.kind === "plural" ? "number"
        : a.kind === "select" ? [...a.options].filter((o) => o !== "other").map((o) => JSON.stringify(o)).concat("(string & {})").join(" | ")
        : "string | number";
      return `${name}: ${type}`;
    });
    const doc = e.note ? `  /** ${e.note.replace(/\*\//g, "*\\/")} */\n` : "";
    return `${doc}  ${JSON.stringify(k)}: ${fields.length ? `{ ${fields.join("; ")} }` : "undefined"};`;
  }).join("\n");
  files["messages.ts"] = `${header}/** Every app message and the arguments it takes. */\nexport interface Messages {\n${types}\n}\nexport type MessageKey = keyof Messages;\n`;

  const langs = config.languages.map((l) => `  ${JSON.stringify(l.code)}: () => require(${JSON.stringify(`./${l.code}`)}).default as Catalog,`).join("\n");
  files["index.ts"] = `${header}/* eslint-disable @typescript-eslint/no-require-imports */
import type { Catalog } from "../runtime";
export type { Messages, MessageKey } from "./messages";

export const SOURCE = ${JSON.stringify(config.source)};
export const LANGUAGES = ${JSON.stringify(config.languages.map(({ code, name, english, locale }) => ({ code, name, english, locale })), null, 2)} as const;
export type LanguageCode = (typeof LANGUAGES)[number]["code"];

declare const require: (id: string) => { default: Catalog };
/** Loaded on first use, so a language nobody picked never costs startup time. */
const loaders: Record<LanguageCode, () => Catalog> = {
${langs}
};
const loaded: Partial<Record<string, Catalog>> = {};
export function catalog(lang: string): Catalog | null {
  if (!(lang in loaders)) return null;
  return (loaded[lang] ??= loaders[lang as LanguageCode]());
}
`;
  return files;
}
