// Generated by `bun run i18n` from packages/i18n/locales/*/native.json. Do not edit.
// The lookup itself, and how the app's language reaches the extensions, is native/KPLocale.swift.
import Foundation

enum L10n {
  enum Backup {
    /// "Invalid backup name"
    static var badName: String { KPL.string("native.backup.badName") }
    /// name is the backup file's name.
    /// "{name} is still downloading from iCloud. Try again in a moment."
    static func downloading(name: String) -> String { KPL.string("native.backup.downloading", name) }
  }
  enum Budget {
    /// Travel mode, a trip with no end date: today is its day-th day.
    /// "Day {day}"
    static func day(day: String) -> String { KPL.string("native.budget.day", day) }
    /// Travel mode: today is day `day` of a `days`-day trip.
    /// "Day {day} of {days}"
    static func dayOf(day: String, days: String) -> String { KPL.string("native.budget.dayOf", day, days) }
    /// Lock Screen widget when there is no budget to name.
    /// "Budget"
    static var fallback: String { KPL.string("native.budget.fallback") }
    /// Under a budget on the watch and in the widgets; amount is formatted money, e.g. "420 PLN".
    /// "{amount} left"
    static func left(amount: String) -> String { KPL.string("native.budget.left", amount) }
    /// Lock Screen inline widget, one short line; name is the budget, amount compact ("1.2k").
    /// "{name}: {amount} left"
    static func namedLeft(name: String, amount: String) -> String { KPL.string("native.budget.namedLeft", name, amount) }
    /// Travel mode: what may be spent per day; amount is formatted money.
    /// "{amount}/day"
    static func perDay(amount: String) -> String { KPL.string("native.budget.perDay", amount) }
  }
  enum Common {
    /// Why a Siri / Shortcut / watch entry could not be saved: the app has never been opened.
    /// "No database on the iPhone yet"
    static var noDatabase: String { KPL.string("native.common.noDatabase") }
    /// Day heading on the watch's History page.
    /// "Today"
    static var today: String { KPL.string("native.common.today") }
    /// Title of a transfer between accounts on the watch's History page.
    /// "Transfer"
    static var transfer: String { KPL.string("native.common.transfer") }
    /// A transaction with no category, on the watch's History page.
    /// "Uncategorized"
    static var uncategorized: String { KPL.string("native.common.uncategorized") }
    /// Day heading on the watch's History page.
    /// "Yesterday"
    static var yesterday: String { KPL.string("native.common.yesterday") }
  }
  enum Complication {
    /// VoiceOver: the complication.
    /// "Add expense"
    static var a11y: String { KPL.string("native.complication.a11y") }
    /// Watch face gallery. Key used as a literal (phone's language).
    /// "Opens Kopiyka ready to type an amount."
    static var description: String { KPL.string("native.complication.description") }
    /// Beside the К on the inline and rectangular complications. Very short.
    /// "Expense"
    static var label: String { KPL.string("native.complication.label") }
    /// Watch face gallery: the complication's name. Key used as a literal (phone's language).
    /// "Add expense"
    static var name: String { KPL.string("native.complication.name") }
  }
  enum Intents {
    /// Siri's answer after logging; amount is formatted money.
    /// "Added {amount}."
    static func added(amount: String) -> String { KPL.string("native.intents.added", amount) }
    /// Siri's answer after logging, when there is more than one account.
    /// "Added {amount} to {account}."
    static func addedAccount(amount: String, account: String) -> String { KPL.string("native.intents.addedAccount", amount, account) }
    /// Siri's answer after logging.
    /// "Added {amount} for {category}."
    static func addedCategory(amount: String, category: String) -> String { KPL.string("native.intents.addedCategory", amount, category) }
    /// Siri's answer after logging, when there is more than one account.
    /// "Added {amount} for {category} to {account}."
    static func addedCategoryAccount(amount: String, category: String, account: String) -> String { KPL.string("native.intents.addedCategoryAccount", amount, category, account) }
    /// Follows the "Added …" sentence; tags is "#trip #work".
    /// "Tags: {tags}."
    static func addedTags(tags: String) -> String { KPL.string("native.intents.addedTags", tags) }
    /// "Another tag?"
    static var anotherTag: String { KPL.string("native.intents.anotherTag") }
    /// "Any tags?"
    static var anyTags: String { KPL.string("native.intents.anyTags") }
    /// Shortcuts: under a category that is itself a folder.
    /// "Folder"
    static var folder: String { KPL.string("native.intents.folder") }
    /// "No accounts yet. Open Kopiyka on your iPhone first."
    static var noAccounts: String { KPL.string("native.intents.noAccounts") }
    /// The choice that saves without a category (Siri, Shortcuts).
    /// "No category"
    static var noCategory: String { KPL.string("native.intents.noCategory") }
    /// Siri asks for tags one by one; this choice ends the list.
    /// "No more tags"
    static var noMoreTags: String { KPL.string("native.intents.noMoreTags") }
    /// "Could not find the total on this receipt."
    static var noTotal: String { KPL.string("native.intents.noTotal") }
    /// "That file is not a photo."
    static var notAPhoto: String { KPL.string("native.intents.notAPhoto") }
    /// "Could not save. Open Kopiyka and try again."
    static var saveFailed: String { KPL.string("native.intents.saveFailed") }
    /// reason is one of the native.writes messages, or a database error.
    /// "Could not save: {reason}. Open Kopiyka and try again."
    static func saveFailedWhy(reason: String) -> String { KPL.string("native.intents.saveFailedWhy", reason) }
    /// After scanning a receipt in another currency; amount is the receipt's own, e.g. "12.50 EUR".
    /// "The receipt says {amount}."
    static func scanOriginal(amount: String) -> String { KPL.string("native.intents.scanOriginal", amount) }
    /// "It is pending — confirm it in Kopiyka."
    static var scanPending: String { KPL.string("native.intents.scanPending") }
    /// After scanning a receipt; merchant is the shop's name.
    /// "Saved {amount} at {merchant}."
    static func scanSaved(amount: String, merchant: String) -> String { KPL.string("native.intents.scanSaved", amount, merchant) }
    /// After scanning a receipt.
    /// "Saved {amount} at {merchant} as {category}."
    static func scanSavedCategory(amount: String, merchant: String, category: String) -> String { KPL.string("native.intents.scanSavedCategory", amount, merchant, category) }
    /// "Which category?"
    static var whichCategory: String { KPL.string("native.intents.whichCategory") }
    enum Add {
      /// Shortcuts action description. Key used as a literal (phone's language).
      /// "Log an expense or income: amount, then category, then tags — without opening the app."
      static var description: String { KPL.string("native.intents.add.description") }
      /// Siri asks for the amount. Used both as a literal and at runtime.
      /// "How much?"
      static var howMuch: String { KPL.string("native.intents.add.howMuch") }
      /// Shortcuts action name. Key used as a literal (phone's language).
      /// "Add expense (no app open)"
      static var title: String { KPL.string("native.intents.add.title") }
    }
    enum Category {
      /// Shortcuts app: the group the Kopiyka actions are listed under. Key used as a literal (phone's language).
      /// "Logging"
      static var logging: String { KPL.string("native.intents.category.logging") }
    }
    enum Entity {
      /// Shortcuts: what an account parameter holds. Key used as a literal (phone's language).
      /// "Account"
      static var account: String { KPL.string("native.intents.entity.account") }
      /// Shortcuts: what a category parameter holds. Key used as a literal (phone's language).
      /// "Category"
      static var category: String { KPL.string("native.intents.entity.category") }
      /// Shortcuts: what a tag parameter holds. Key used as a literal (phone's language).
      /// "Tag"
      static var tag: String { KPL.string("native.intents.entity.tag") }
    }
    enum Kind {
      /// Shortcuts: one of the two types. Key used as a literal (phone's language).
      /// "Expense"
      static var expense: String { KPL.string("native.intents.kind.expense") }
      /// Shortcuts: one of the two types. Key used as a literal (phone's language).
      /// "Income"
      static var income: String { KPL.string("native.intents.kind.income") }
      /// Shortcuts: the name of the expense/income choice. Key used as a literal (phone's language).
      /// "Type"
      static var type: String { KPL.string("native.intents.kind.type") }
    }
    enum Open {
      /// Shortcuts action description. Key used as a literal (phone's language).
      /// "Opens Kopiyka on the new-expense sheet."
      static var description: String { KPL.string("native.intents.open.description") }
      /// Shortcuts action name. Key used as a literal (phone's language).
      /// "Add expense in the app"
      static var title: String { KPL.string("native.intents.open.title") }
    }
    enum Param {
      /// "Account"
      static var account: String { KPL.string("native.intents.param.account") }
      /// "Amount"
      static var amount: String { KPL.string("native.intents.param.amount") }
      /// "Ask for category and tags"
      static var ask: String { KPL.string("native.intents.param.ask") }
      /// "Message"
      static var body: String { KPL.string("native.intents.param.body") }
      /// "Card"
      static var card: String { KPL.string("native.intents.param.card") }
      /// "Category"
      static var category: String { KPL.string("native.intents.param.category") }
      /// "Location"
      static var location: String { KPL.string("native.intents.param.location") }
      /// "Optional. Add “Get Current Location” before this action and put its result here, so the entry remembers where you paid."
      static var locationHelp: String { KPL.string("native.intents.param.locationHelp") }
      /// "Merchant"
      static var merchant: String { KPL.string("native.intents.param.merchant") }
      /// "Note"
      static var note: String { KPL.string("native.intents.param.note") }
      /// "Notification"
      static var notification: String { KPL.string("native.intents.param.notification") }
      /// "Pending"
      static var pending: String { KPL.string("native.intents.param.pending") }
      /// "Receipt photo"
      static var photo: String { KPL.string("native.intents.param.photo") }
      /// "Subtitle"
      static var subtitle: String { KPL.string("native.intents.param.subtitle") }
      /// "Tags"
      static var tags: String { KPL.string("native.intents.param.tags") }
      /// "Title"
      static var title: String { KPL.string("native.intents.param.title") }
      /// "Type"
      static var type: String { KPL.string("native.intents.param.type") }
    }
    enum Payment {
      /// Shortcuts action description. Key used as a literal (phone's language). “When I receive a notification” and Notification are what the Shortcuts app calls them in this language.
      /// "Log a payment from a bank or Wallet notification. Made for the Shortcuts “When I receive a notification” automation: pass its Notification variable."
      static var description: String { KPL.string("native.intents.payment.description") }
      /// "No accounts in Kopiyka yet. Open it on your iPhone first."
      static var noAccounts: String { KPL.string("native.intents.payment.noAccounts") }
      /// Written into the entry's note when a foreign charge could not be converted; amount is the original, e.g. "36.00 EUR".
      /// "{amount} — no exchange rate, set the amount"
      static func noRate(amount: String) -> String { KPL.string("native.intents.payment.noRate", amount) }
      /// "Kopiyka could not save that payment. Open the app and add it by hand."
      static var saveFailed: String { KPL.string("native.intents.payment.saveFailed") }
      /// reason is one of the native.writes / native.common.noDatabase messages, or a database error.
      /// "Kopiyka could not save that payment: {reason}. Open the app and add it by hand."
      static func saveFailedWhy(reason: String) -> String { KPL.string("native.intents.payment.saveFailedWhy", reason) }
      /// Shortcuts action name. Key used as a literal (phone's language).
      /// "Log payment from an app notification"
      static var title: String { KPL.string("native.intents.payment.title") }
      /// Shortcuts error: the notification names money but no amount could be read. The screen names must match the app's Settings.
      /// "Kopiyka could not read an amount out of that notification. Settings → Automate with Shortcut shows what it expects."
      static var unreadable: String { KPL.string("native.intents.payment.unreadable") }
    }
    enum Scan {
      /// Shortcuts action description. Key used as a literal (phone's language).
      /// "Photograph a receipt: the amount, shop, items and category are read on the device and saved as a pending expense."
      static var description: String { KPL.string("native.intents.scan.description") }
      /// Shortcuts action name. Key used as a literal (phone's language).
      /// "Scan receipt"
      static var title: String { KPL.string("native.intents.scan.title") }
    }
    enum Shortcut {
      /// "Add expense"
      static var addExpense: String { KPL.string("native.intents.shortcut.addExpense") }
      /// "Expense in app"
      static var expenseInApp: String { KPL.string("native.intents.shortcut.expenseInApp") }
      /// "Log payment"
      static var logPayment: String { KPL.string("native.intents.shortcut.logPayment") }
      /// "Scan receipt"
      static var scanReceipt: String { KPL.string("native.intents.shortcut.scanReceipt") }
    }
  }
  enum Notify {
    /// In the notification body, after the category: the category was guessed. Lowercase, one word if possible.
    /// "guess"
    static var guess: String { KPL.string("native.notify.guess") }
    /// Notification title after the automation logged a payment, when no shop name was read.
    /// "Payment logged"
    static var logged: String { KPL.string("native.notify.logged") }
    /// In the notification body: the entry waits in the Pending queue. Lowercase.
    /// "pending"
    static var pending: String { KPL.string("native.notify.pending") }
    /// Notification title after the automation logged income, when no payer name was read.
    /// "Payment received"
    static var received: String { KPL.string("native.notify.received") }
  }
  enum Receipt {
    /// In the note a scanned receipt writes: "Żabka · 2 items: …".
    /// "{count, plural, one {# item} other {# items}}"
    static func items(count: Int) -> String { KPL.string("native.receipt.items", count) }
    /// "The photo could not be read."
    static var noImage: String { KPL.string("native.receipt.noImage") }
    /// The receipt note when its currency could not be converted; currency is a code like EUR.
    /// "{note} (in {currency}, no exchange rate)"
    static func noRate(note: String, currency: String) -> String { KPL.string("native.receipt.noRate", note, currency) }
    /// "No text found. Hold the phone flat over the receipt with good light."
    static var noText: String { KPL.string("native.receipt.noText") }
    /// In the note a scanned receipt writes, when more was handed over than the total.
    /// "paid {amount}"
    static func paid(amount: String) -> String { KPL.string("native.receipt.paid", amount) }
    /// In the note a scanned receipt writes; lowercase, it follows a ·.
    /// "total {amount}"
    static func total(amount: String) -> String { KPL.string("native.receipt.total", amount) }
    /// The shop's name when none could be read off the receipt; saved as the payee.
    /// "Receipt"
    static var untitled: String { KPL.string("native.receipt.untitled") }
  }
  enum Sample {
    /// "Account"
    static var account: String { KPL.string("native.sample.account") }
    /// "Food"
    static var food: String { KPL.string("native.sample.food") }
    /// "Fun"
    static var fun: String { KPL.string("native.sample.fun") }
  }
  enum Watch {
    /// VoiceOver: the keypad page.
    /// "Add expense"
    static var addExpense: String { KPL.string("native.watch.addExpense") }
    /// VoiceOver: the typed amount with its currency.
    /// "Amount {amount}"
    static func amount(amount: String) -> String { KPL.string("native.watch.amount", amount) }
    /// VoiceOver: the . key.
    /// "Decimal point"
    static var decimalPoint: String { KPL.string("native.watch.decimalPoint") }
    /// VoiceOver: the ⌫ key.
    /// "Delete last digit"
    static var deleteDigit: String { KPL.string("native.watch.deleteDigit") }
    /// VoiceOver hint on the amount.
    /// "Next: choose a category"
    static var hintNext: String { KPL.string("native.watch.hintNext") }
    /// VoiceOver hint on the empty amount.
    /// "Type an amount on the keypad below"
    static var hintType: String { KPL.string("native.watch.hintType") }
    /// "Open Kopiyka on your iPhone once to sync."
    static var syncOnce: String { KPL.string("native.watch.syncOnce") }
    enum Budgets {
      /// VoiceOver.
      /// "{name}, {amount} left"
      static func budgetA11y(name: String, amount: String) -> String { KPL.string("native.watch.budgets.budgetA11y", name, amount) }
      /// "No budgets yet. Add one on your iPhone."
      static var empty: String { KPL.string("native.watch.budgets.empty") }
      /// Section heading.
      /// "Travel mode"
      static var travel: String { KPL.string("native.watch.budgets.travel") }
      /// VoiceOver; name is the trip, day is "Day 3 of 7".
      /// "Travel {name}, {amount} left, {day}"
      static func travelA11y(name: String, amount: String, day: String) -> String { KPL.string("native.watch.budgets.travelA11y", name, amount, day) }
    }
    enum Category {
      /// "Categories sync from your iPhone."
      static var empty: String { KPL.string("native.watch.category.empty") }
      /// Under a category that is itself a folder.
      /// "Folder"
      static var folder: String { KPL.string("native.watch.category.folder") }
      /// VoiceOver hint.
      /// "Choose this category"
      static var hint: String { KPL.string("native.watch.category.hint") }
      /// VoiceOver: a category and its folder.
      /// "{name}, in {folder}"
      static func inFolder(name: String, folder: String) -> String { KPL.string("native.watch.category.inFolder", name, folder) }
      /// VoiceOver: a top-level category.
      /// "{name} folder"
      static func isFolder(name: String) -> String { KPL.string("native.watch.category.isFolder", name) }
      /// VoiceOver: the category suggested for this spot; label is one of the two above.
      /// "Near here: {label}"
      static func near(label: String) -> String { KPL.string("native.watch.category.near", label) }
      /// "No category"
      static var none: String { KPL.string("native.watch.category.none") }
      /// VoiceOver hint.
      /// "Save without a category"
      static var noneHint: String { KPL.string("native.watch.category.noneHint") }
      /// "Category"
      static var title: String { KPL.string("native.watch.category.title") }
    }
    enum History {
      /// VoiceOver, inside a row's description; time like 14:05.
      /// "at {time}"
      static func a11yAt(time: String) -> String { KPL.string("native.watch.history.a11yAt", time) }
      /// VoiceOver, inside a row's description; list is comma-separated.
      /// "tags {list}"
      static func a11yTags(list: String) -> String { KPL.string("native.watch.history.a11yTags", list) }
      /// VoiceOver, inside a row's description.
      /// "waiting for iPhone"
      static var a11yWaiting: String { KPL.string("native.watch.history.a11yWaiting") }
      /// "Nothing today or yesterday."
      static var empty: String { KPL.string("native.watch.history.empty") }
      /// Under an entry the phone has not received yet.
      /// "Waiting for iPhone"
      static var waiting: String { KPL.string("native.watch.history.waiting") }
    }
    enum Intent {
      /// Key used as a literal (phone's language).
      /// "Open Kopiyka on the watch ready to type an amount."
      static var description: String { KPL.string("native.watch.intent.description") }
      /// Watch action (Action button, Siri). Key used as a literal (phone's language).
      /// "Log expense"
      static var title: String { KPL.string("native.watch.intent.title") }
    }
    enum Status {
      /// "iPhone connected"
      static var connected: String { KPL.string("native.watch.status.connected") }
      /// "Entries are saved on the iPhone at once"
      static var connectedDetail: String { KPL.string("native.watch.status.connectedDetail") }
      /// "Data from iPhone"
      static var data: String { KPL.string("native.watch.status.data") }
      /// "Last entry"
      static var lastEntry: String { KPL.string("native.watch.status.lastEntry") }
      /// "Data from iPhone" when nothing ever arrived.
      /// "never"
      static var never: String { KPL.string("native.watch.status.never") }
      /// "Nothing waiting"
      static var nothingWaiting: String { KPL.string("native.watch.status.nothingWaiting") }
      /// "All watch entries delivered"
      static var nothingWaitingDetail: String { KPL.string("native.watch.status.nothingWaitingDetail") }
      /// "Refresh"
      static var refresh: String { KPL.string("native.watch.status.refresh") }
      /// VoiceOver hint.
      /// "Asks the iPhone for the latest accounts, categories and history"
      static var refreshHint: String { KPL.string("native.watch.status.refreshHint") }
      /// "Refreshing…"
      static var refreshing: String { KPL.string("native.watch.status.refreshing") }
      /// "Status"
      static var title: String { KPL.string("native.watch.status.title") }
      /// "iPhone not reachable"
      static var unreachable: String { KPL.string("native.watch.status.unreachable") }
      /// "Entries wait on the watch until it is back"
      static var unreachableDetail: String { KPL.string("native.watch.status.unreachableDetail") }
      /// "{count, plural, one {# waiting for iPhone} other {# waiting for iPhone}}"
      static func waiting(count: Int) -> String { KPL.string("native.watch.status.waiting", count) }
      /// "Delivered automatically when the iPhone is near"
      static var waitingDetail: String { KPL.string("native.watch.status.waitingDetail") }
    }
    enum Tags {
      /// VoiceOver, after the save hint.
      /// "{count, plural, one {# tag} other {# tags}}"
      static func count(count: Int) -> String { KPL.string("native.watch.tags.count", count) }
      /// "Double tap to add this tag"
      static var hintAdd: String { KPL.string("native.watch.tags.hintAdd") }
      /// "Double tap to remove this tag"
      static var hintRemove: String { KPL.string("native.watch.tags.hintRemove") }
      /// First row: save with no tags.
      /// "No tags"
      static var none: String { KPL.string("native.watch.tags.none") }
      /// VoiceOver value of an unticked tag.
      /// "not selected"
      static var notSelected: String { KPL.string("native.watch.tags.notSelected") }
      /// "Other tags"
      static var other: String { KPL.string("native.watch.tags.other") }
      /// VoiceOver hint; amount is formatted money.
      /// "Save {amount}"
      static func save(amount: String) -> String { KPL.string("native.watch.tags.save", amount) }
      /// Small button over the list once tags are ticked.
      /// "{count, plural, one {Save · # tag} other {Save · # tags}}"
      static func saveCount(count: Int) -> String { KPL.string("native.watch.tags.saveCount", count) }
      /// VoiceOver hint.
      /// "Save {amount} for {category}"
      static func saveFor(amount: String, category: String) -> String { KPL.string("native.watch.tags.saveFor", amount, category) }
      /// VoiceOver value of a ticked tag.
      /// "selected"
      static var selected: String { KPL.string("native.watch.tags.selected") }
      /// "Tags"
      static var title: String { KPL.string("native.watch.tags.title") }
      /// First row in travel mode: save with only the trip's tag.
      /// "Just the travel tag"
      static var tripOnly: String { KPL.string("native.watch.tags.tripOnly") }
      /// Section of tags often used with the chosen category.
      /// "Used with {category}"
      static func usedWith(category: String) -> String { KPL.string("native.watch.tags.usedWith", category) }
    }
    enum Write {
      /// Status page after an entry was saved; also read by VoiceOver.
      /// "Added {amount}"
      static func added(amount: String) -> String { KPL.string("native.watch.write.added", amount) }
      /// Status page after an entry was saved.
      /// "Added {amount} for {category}"
      static func addedFor(amount: String, category: String) -> String { KPL.string("native.watch.write.addedFor", amount, category) }
      /// "Delete queued for iPhone"
      static var deleteQueued: String { KPL.string("native.watch.write.deleteQueued") }
      /// "Deleted"
      static var deleted: String { KPL.string("native.watch.write.deleted") }
      /// "iPhone could not save"
      static var failed: String { KPL.string("native.watch.write.failed") }
      /// reason is one of the native.writes messages, in the phone's app language.
      /// "iPhone could not save: {reason}"
      static func failedWhy(reason: String) -> String { KPL.string("native.watch.write.failedWhy", reason) }
      /// "Not paired with an iPhone"
      static var notPaired: String { KPL.string("native.watch.write.notPaired") }
      /// Status page: saved on the watch, sent when the phone is near.
      /// "Queued for iPhone: {amount}"
      static func queued(amount: String) -> String { KPL.string("native.watch.write.queued", amount) }
      /// Status page.
      /// "Queued for iPhone: {amount} for {category}"
      static func queuedFor(amount: String, category: String) -> String { KPL.string("native.watch.write.queuedFor", amount, category) }
    }
  }
  enum Widget {
    enum Budgets {
      /// Widget gallery. Key used as a literal (phone's language).
      /// "What is left in each budget this month."
      static var description: String { KPL.string("native.widget.budgets.description") }
      /// "No budgets yet"
      static var empty: String { KPL.string("native.widget.budgets.empty") }
      /// Widget gallery. Key used as a literal (phone's language).
      /// "Budgets"
      static var name: String { KPL.string("native.widget.budgets.name") }
    }
    enum Lock {
      /// Widget gallery. Key used as a literal (phone's language).
      /// "Remaining amount in your first budget."
      static var description: String { KPL.string("native.widget.lock.description") }
      /// Widget gallery. Key used as a literal (phone's language).
      /// "Budget left"
      static var name: String { KPL.string("native.widget.lock.name") }
    }
    enum NetWorth {
      /// Widget gallery. Key used as a literal (phone's language).
      /// "Balances across your accounts."
      static var description: String { KPL.string("native.widget.netWorth.description") }
      /// Widget gallery. Key used as a literal (phone's language).
      /// "Net worth"
      static var name: String { KPL.string("native.widget.netWorth.name") }
      /// "Net worth"
      static var title: String { KPL.string("native.widget.netWorth.title") }
    }
  }
  enum Writes {
    /// "the app did not answer"
    static var noAnswer: String { KPL.string("native.writes.noAnswer") }
    /// "not found"
    static var notFound: String { KPL.string("native.writes.notFound") }
    /// "the app is not running"
    static var notRunning: String { KPL.string("native.writes.notRunning") }
    /// "nothing to fill in"
    static var nothingToFill: String { KPL.string("native.writes.nothingToFill") }
    /// "the app reloaded"
    static var reloaded: String { KPL.string("native.writes.reloaded") }
  }
}
