/**
 * Launch screen = the page background with the silhouette of the Transactions screen on it: no
 * text, just the shapes (assets/splash, generated by scripts/make-splash.mjs). The native splash is
 * held up until the first screen has painted (src/lib/boot.ts), so it fades straight into the real
 * thing with no blank frame and no JS-drawn stand-in in between.
 *
 * On an iPhone, `SplashTop` is pinned under the status bar and `SplashBottom` to the bottom of the
 * screen, each scaled to its width. An iPad lays out differently — tab bar at the top, a centred
 * column, the floating buttons in the corner — so it has pieces of its own, anchored the same way
 * as the real ones (see `IMAGES` below and scripts/make-splash.mjs).
 *
 * expo-splash-screen 57 only writes the `SplashScreenBackground` colour into the storyboard when an
 * `image` is configured; with no image it leaves the template's white `systemBackgroundColor` and the
 * dangling centre constraints of the removed image view. This mod is listed before that plugin (mods on
 * the same file run newest-first, and the splash plugin's own base mod must be registered last) and fixes
 * both (light and dark come from the `SplashScreenBackground` colorset the splash plugin still generates).
 */
const fs = require("fs");
const path = require("path");
const { withDangerousMod, IOSConfig } = require("expo/config-plugins");

// The package's exports map hides its plugin internals; absolute paths bypass it.
const pluginDir = path.join(path.dirname(require.resolve("expo-splash-screen/package.json")), "plugin/build");
const { withIosSplashScreenStoryboard } = require(path.join(pluginDir, "withIosSplashScreenStoryboard.js"));
const { parseColor } = require(path.join(pluginDir, "InterfaceBuilder.js"));

/**
 * Every image, its size in points (as scripts/make-splash.mjs draws it) and how it is anchored. The
 * iPhone pieces scale to the screen's width, up to a large phone's; the iPad ones are drawn at their
 * real size. Each image set exists for one idiom only, so on the other device its view is empty.
 * `safe` is the safe area's top (under the status bar), `root` the screen.
 */
const MAX_W = 440;
const IMAGES = {
  // iPhone
  SplashTop: { w: 402, h: 720, scaled: true, pin: [["top", "safe", "top", 0]] },
  SplashBottom: { w: 402, h: 180, scaled: true, pin: [["bottom", "root", "bottom", 0]] },
  // iPad: the tab bar centred at the top, the large title at the left, Select at the right, the
  // centred content column under them, and the floating buttons in the bottom-right corner.
  SplashPadTabs: { w: 477, h: 44, pin: [["centerX", "root", "centerX", 0], ["top", "safe", "top", 8]] },
  SplashPadSelect: { w: 64, h: 44, pin: [["trailing", "root", "trailing", -11], ["top", "safe", "top", 8]] },
  SplashPadTitle: { w: 210, h: 34, pin: [["leading", "root", "leading", 21], ["top", "safe", "top", 70]] },
  SplashPadColumn: { w: 780, h: 1400, pin: [["centerX", "root", "centerX", 0], ["top", "safe", "top", 118]] },
  SplashPadButtons: { w: 200, h: 180, pin: [["trailing", "root", "trailing", -16], ["bottom", "root", "bottom", -96]] },
};

const c = (id, first, firstAttr, second, secondAttr, extra = {}) =>
  ({ $: { firstItem: first, firstAttribute: firstAttr, ...(second ? { secondItem: second, secondAttribute: secondAttr } : {}), id, ...extra } });

function layout(view) {
  const root = view.$.id;
  const safe = view.viewLayoutGuide?.[0]?.$?.id ?? root;
  const target = { root, safe };
  const constraints = [];
  const views = Object.entries(IMAGES).map(([name, img]) => {
    const id = `KP-${name}`;
    if (img.scaled) {
      constraints.push(
        c(`${id}-cx`, id, "centerX", root, "centerX"),
        c(`${id}-w`, id, "width", root, "width", { priority: "750" }),
        c(`${id}-max`, id, "width", null, null, { relation: "lessThanOrEqual", constant: String(MAX_W) }),
        c(`${id}-ratio`, id, "width", id, "height", { multiplier: `${img.w}:${img.h}` }),
      );
    } else {
      constraints.push(
        c(`${id}-w`, id, "width", null, null, { constant: String(img.w) }),
        c(`${id}-h`, id, "height", null, null, { constant: String(img.h) }),
      );
    }
    for (const [attr, to, toAttr, constant] of img.pin) {
      constraints.push(c(`${id}-${attr}`, id, attr, target[to], toAttr, constant ? { constant: String(constant) } : {}));
    }
    return {
      $: { clipsSubviews: "YES", userInteractionEnabled: "NO", contentMode: img.scaled ? "scaleAspectFit" : "scaleToFill", image: name, translatesAutoresizingMaskIntoConstraints: "NO", id },
      rect: [{ $: { key: "frame", x: "0.0", y: "0.0", width: String(img.w), height: String(img.h) } }],
    };
  });
  view.subviews = [{ imageView: views }];
  view.constraints = [{ constraint: constraints }];
}

/** @type {import('expo/config-plugins').ConfigPlugin<{ backgroundColor: string }>} */
module.exports = (config, { backgroundColor }) => {
  config = withDangerousMod(config, ["ios", async (cfg) => {
    const catalog = path.join(IOSConfig.Paths.getSourceRoot(cfg.modRequest.projectRoot), "Images.xcassets");
    for (const name of Object.keys(IMAGES)) {
      const from = path.join(cfg.modRequest.projectRoot, "assets", "splash", `${name}.imageset`);
      const to = path.join(catalog, `${name}.imageset`);
      await fs.promises.rm(to, { recursive: true, force: true });
      await fs.promises.cp(from, to, { recursive: true });
    }
    return cfg;
  }]);
  return withIosSplashScreenStoryboard(config, (c) => {
    const xml = c.modResults;
    const view = xml.document.scenes[0]?.scene[0]?.objects[0]?.viewController[0]?.view[0];
    if (view) {
      layout(view);
      view.color = [{ $: { key: "backgroundColor", name: "SplashScreenBackground" } }];
    }
    const resources = xml.document.resources?.[0];
    if (resources) {
      delete resources.systemColor;
      resources.image = Object.entries(IMAGES).map(([name, img]) => ({ $: { name, width: String(img.w), height: String(img.h) } }));
      const { rgb } = parseColor(backgroundColor);
      resources.namedColor = [{
        $: { name: "SplashScreenBackground" },
        color: [{ $: { alpha: "1.000", blue: rgb.blue, green: rgb.green, red: rgb.red, customColorSpace: "sRGB", colorSpace: "custom" } }],
      }];
    }
    return c;
  });
};
